<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260324140058 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(30) NOT NULL, montant_total NUMERIC(10, 2) NOT NULL, adresse_livraison TEXT DEFAULT NULL, panier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6EEAA67DF77D927C ON commande (panier_id)');
        $this->addSql('CREATE TABLE ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prix_supplement NUMERIC(6, 2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE panier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(20) NOT NULL, montant_total NUMERIC(10, 2) DEFAULT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_24CC0DF2FB88E14F ON panier (utilisateur_id)');
        $this->addSql('CREATE TABLE panier_produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, panier_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D31F28A6F77D927C ON panier_produit (panier_id)');
        $this->addSql('CREATE INDEX IDX_D31F28A6F347EFB ON panier_produit (produit_id)');
        $this->addSql('CREATE TABLE panier_produit_ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(10) NOT NULL, panier_produit_id INT NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B64D47786BE1476E ON panier_produit_ingredient (panier_produit_id)');
        $this->addSql('CREATE INDEX IDX_B64D4778933FE08C ON panier_produit_ingredient (ingredient_id)');
        $this->addSql('CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prix NUMERIC(8, 2) NOT NULL, description TEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, categorie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_29A5EC27BCF5E72D ON produit (categorie_id)');
        $this->addSql('CREATE TABLE produit_ingredient (produit_id INT NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (produit_id, ingredient_id))');
        $this->addSql('CREATE INDEX IDX_C297417DF347EFB ON produit_ingredient (produit_id)');
        $this->addSql('CREATE INDEX IDX_C297417D933FE08C ON produit_ingredient (ingredient_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, telephone VARCHAR(20) DEFAULT NULL, role_metier VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EMAIL ON utilisateur (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DF77D927C FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF2FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE panier_produit ADD CONSTRAINT FK_D31F28A6F77D927C FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE panier_produit ADD CONSTRAINT FK_D31F28A6F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE panier_produit_ingredient ADD CONSTRAINT FK_B64D47786BE1476E FOREIGN KEY (panier_produit_id) REFERENCES panier_produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE panier_produit_ingredient ADD CONSTRAINT FK_B64D4778933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE produit_ingredient ADD CONSTRAINT FK_C297417DF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit_ingredient ADD CONSTRAINT FK_C297417D933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DF77D927C');
        $this->addSql('ALTER TABLE panier DROP CONSTRAINT FK_24CC0DF2FB88E14F');
        $this->addSql('ALTER TABLE panier_produit DROP CONSTRAINT FK_D31F28A6F77D927C');
        $this->addSql('ALTER TABLE panier_produit DROP CONSTRAINT FK_D31F28A6F347EFB');
        $this->addSql('ALTER TABLE panier_produit_ingredient DROP CONSTRAINT FK_B64D47786BE1476E');
        $this->addSql('ALTER TABLE panier_produit_ingredient DROP CONSTRAINT FK_B64D4778933FE08C');
        $this->addSql('ALTER TABLE produit DROP CONSTRAINT FK_29A5EC27BCF5E72D');
        $this->addSql('ALTER TABLE produit_ingredient DROP CONSTRAINT FK_C297417DF347EFB');
        $this->addSql('ALTER TABLE produit_ingredient DROP CONSTRAINT FK_C297417D933FE08C');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE ingredient');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE panier_produit');
        $this->addSql('DROP TABLE panier_produit_ingredient');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE produit_ingredient');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
